// File auto-generated by build_version.js
/* eslint-disable eol-last */
module.exports = {
  'version': '2019.7.15',
  'year': 2019,
  'month': 7,
  'buildTotal': 307,
  'buildThisYear': 15,
  'buildThisMonth': 15
}
