// File auto-generated by build_version.js
/* eslint-disable eol-last */
module.exports = {
  'version': '2019.7.11',
  'year': 2019,
  'month': 7,
  'buildTotal': 303,
  'buildThisYear': 11,
  'buildThisMonth': 11
}
