// File auto-generated by build_version.js
/* eslint-disable eol-last */
module.exports = {
  'version': '2019.8.33',
  'year': 2019,
  'month': 8,
  'buildTotal': 341,
  'buildThisYear': 49,
  'buildThisMonth': 33
}
